export const createUsersTable = `
  CREATE TYPE user_status AS ENUM ('validated', 'unvalidated', 'block');
  CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    group_id SERIAL,
    thumb_file SERIAL,
    signature_file SERIAL,
    status user_status NOT NULL DEFAULT 'unvalidated'::user_status,
    email character varying(255) NOT NULL UNIQUE,
    login_id character varying(255) UNIQUE,
    old_password character varying(255),
    password character varying(255),
    name character varying(255) NOT NULL,
    realname character varying(255),
    introduce text,
    phone character varying(255),
    data jsonb,
    allowed_marketing boolean NOT NULL DEFAULT false,
    allowed_news_email boolean NOT NULL DEFAULT true,
    is_instructor boolean NOT NULL DEFAULT false,
    is_admin boolean NOT NULL DEFAULT false,
    buyer_name character varying(255),
    buyer_tel character varying(255),
    buyer_email character varying(255),
    accessed_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_allowed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    supervisor jsonb DEFAULT '{}'::jsonb,
    category_ids jsonb DEFAULT '[]'::jsonb,
    e_mode character varying(255),
    email_token character varying(255) UNIQUE,
    _point integer NOT NULL DEFAULT 0,
    be_instructor_at timestamp with time zone,
    spam_type jsonb NOT NULL DEFAULT '{}'::jsonb,
    inst_certified_at timestamp with time zone,
    slug character varying(255) UNIQUE,
    inactive_at timestamp with time zone,
    mobile character varying(20) UNIQUE,
    country_code character varying(10),
    search_name character varying(255)
  );
`
